module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "format",
        "perf",
        "test",
        "chore",
        "revert",
        "build",
        "ci",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "app",
        "widgets",
        "clock",
        "calendar",
        "weather",
        "metrics",
        "api",
        "config",
        "assets",
        "deps",
        "docs",
      ],
    ],
    "header-max-length": [2, "always", 120],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "subject-empty": [2, "never"],
    "subject-case": [0],
  },
};
